### ISSUE TITLE
Add the LICENSE and README files of devvm repo

### ISSUE THREAD

**Issue by hhebbo** [spryker/saltstack#11] opened 2016-03-04 16:34 UTC
- [ ] Add the LICENSE file of devvm repo when installing the vm
- [ ] Add the README file of devvm repo when installing the vm

**Comment by marek-obuchowicz** [comment] 2017-11-09 18:34
Closing as this repo will be archived. Contents are moved to `devvm` repository. If the issue is still relevant, please move to jira.

**Closed as completed by marek-obuchowicz** 2017-11-09 18:34 UTC
Labels: enhancement
